[package]
name = "termion-tokio"
version = "0.1.0"
authors = ["Kayo Phoenix <kayo@illumium.org>"]

[dependencies]
bytes = "0.4"
futures-preview = "0.3.0-alpha.19"
termion = "1"
tokio = "0.2.0-alpha.6"
